FROM rancher/hardened-build-base:v1.26.5b2@sha256:e9ea50cbc319e0034a73aa550e64e18e8cb4a6738afe9c3ad9fa090871878c5e AS builder
WORKDIR /app

COPY . .
RUN go mod download

RUN CGO_ENABLED=0 go build -o proxy ./cmd/proxy

FROM scratch
COPY --from=builder /app/proxy .
CMD ["./proxy"]
